Change Organization model and add API
minvws/nl-kat-rocky pull request #109
Opened 2023-01-04 08:49 UTC by dekkers

Remove the organization signal_username and signal_group_id fields and some code that references those fields. Not everything related to signal / miauw has been cleaned up yet.

Change Organization code to a lower-case unicode slug field and increase length to 32.

Add tags to Organization models using django-tagulous with a custom tag model with colors and borders.

Add a REST API using django-rest-framework.

2023-01-04 13:08 UTC, underdarknl commented on .ci/rocky_db_seed.json
> +      "code": "_dev"
Do we still need this _dev in here? I thinik the onboarding flow now creates the first organization.

2023-01-04 13:14 UTC, underdarknl requested changes
I really don't wat to include jquery, bootstrap and some other JS libraries for a html interface that is used for the restfull api's.

2023-01-04 14:00 UTC, dekkers commented
> I really don't wat to include jquery, bootstrap and some other JS libraries for a html interface that is used for the restfull api's.

I think including the javascript in the package is a lot better than what we currently have with FastAPI that loads the latest version of all the javascript from a third party server (just look at /docs or /redoc on one of our FastAPI services).

I think the browsable API is useful for people who want to use the API, but maybe we should make this a setting and disable the browsable API by default?

2023-01-05 10:34 UTC, underdarknl commented
Lets disable the browsable api then. If someone needs it  they can carry the burden of keeping things up to date.
For fastApi api's I feel the same way, although those are not internet connected as easily as rocky is. Minimizing dependencies, especially on the frontend for parts that are hardly used should always be a top priority for a security product like OpenKAT

2023-01-05 14:04 UTC, dekkers commented
I have added BROWSABLE_API env var to control whether the browsable API is enabled. It will default to False in production and True when DEBUG is True.

2023-01-05 21:46 UTC, underdarknl approved these changes

2023-01-05 21:46 UTC, merged