Removed old references to miauw and signal
minvws/nl-kat-rocky pull request #179
Opened 2023-01-23 14:29 UTC by ammar92

## Changes
Removed some dead code and references to Miauw and Signal

## Proof
Searching miauw and signal using find *usages option* and grep yields no results anymore.

## Good to know
- Does this PR introduce or depend on API-incompatible changes? If yes: what do other users/developers need to do or confirm before merging?
  - No
- Does this PR depend on a specific version of a library?
  - No
- Does this PR require config, setup, or `.env` changes?
  - Yes, settings related to miauw can be removed safely

## Checklist for author(s):
- [x] This PR comes from a `feature` or `hotfix` branch, in line with our git branching strategy;
- [ ] I have squashed all commits before merging this PR;
- [x] This PR is "bite-sized" and only focuses on a single issue, problem, or feature;
- [ ] If a non-trivial PR: This PR is properly linked to an issue on the project board;
- [ ] If a non-trivial PR: I have added screenshots or some other proof that my code does what it is supposed to do;
- [x] I am not reinventing the wheel: there is no high-quality library that already has this feature;
- [x] I have changed the example `.env` files if I added, removed, or changed any config options, and I have informed others that they need to modify their `.env` files if required;
- [x] I have performed a self-review of my own code;
- [ ] I have commented my code, particularly in hard-to-understand areas;
- [ ] I have made corresponding changes to the documentation, if necessary;
- [ ] I have written unit, integration, and end-to-end tests for the change that I made;

2023-01-25 13:59 UTC, Donnype requested changes

2023-01-25 13:59 UTC, Donnype commented on rocky/views/organization_edit.py
>          return reverse("organization_detail", kwargs={"pk": self.object.id})
```suggestion
        return reverse("organization_detail", kwargs={"organization_code": self.object.code})
```

2023-01-25 13:59 UTC, Donnype commented on rocky/views/organization_edit.py
>          return reverse("organization_detail", kwargs={"pk": self.object.id})
Same at line 64 (or 30 in new version)

2023-01-25 13:59 UTC, Donnype commented on rocky/views/organization_edit.py
>          return reverse("organization_detail", kwargs={"pk": self.object.id})
And at line 84 (or 50 in new version) where we need to do organization.code

2023-01-25 16:12 UTC, Donnype submitted a review, later dismissed

2023-01-26 15:02 UTC, Donnype approved these changes

2023-01-26 15:45 UTC, underdarknl approved these changes

2023-01-26 15:45 UTC, merged